server:
  context-path: /
  servlet-path: /config
spring:
   data.mongodb: 
       database: local
       host: 192.168.99.100
       port: 32768
   profiles.active: mongo
   jpa.show-sql: true
   
   