server:
  context-path: /
  servlet-path: /config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpriego/skeleton-config.git
          username: gpriego
          password: M1thr@nd1r
          search-paths: skeleton-config

   